name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Agent (GitHub -> EC2)
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Run Deployment Script on EC2
        env:
          CI: false   # prevents React build from failing due to warnings
        run: |
          ssh -T -A \
            -o ServerAliveInterval=60 \
            -o ServerAliveCountMax=10 \
            -o StrictHostKeyChecking=no \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
              cd /home/ubuntu/
              ./deploy.sh main
          EOF
